title: Aptly Blog
email: jayakumar.e@gmail.com
description: Blog portal of Aptly Technologies
author: Jayakumar
baseurl: "/blog"
url: "#"

# Social Profiles
twitter_username: uname
github_username: uname
facebook_username: uname
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
